media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: published, label: Published Date, type: datetime }
      - { name: slug, label: URL Slug, type: string, required: true, hint: "用于生成文章URL，如: my-first-blog-post" }
      - { name: description, label: Description, type: string }
      - { name: image, label: Cover Image, type: image }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: category, label: Category, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/content/spec/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
